`timescale 1ns / 1ps

module elevator_top
(
    input clk,
    input rst,

    input electricity,
    input generator,
    input up,
    input down,
    input [3:0] floor,
    input e_stop,
    input [8:0] weight,
    input light,
    input fan,
    input request_valid,

    output m_up,
    output m_down,
    output d_open,
    output d_close,
    output light_on,
    output fan_on,
    output alarm_on
);

// =========================================================
// FIFO SIGNALS
// =========================================================
wire fifo_wr_en;
reg  fifo_rd_en;

wire fifo_full;
wire fifo_empty;

wire [3:0] fifo_data_out;
//to avoid continuos reads we use fifo data valid , it is 1 when data is already read from fifo and 0 when data is not read from fifo
wire fifo_data_valid;


// =========================================================
// ELEVATOR SIGNALS
// =========================================================
wire elevator_idle;
wire [3:0] current_floor;
wire [3:0] current_state;


// =========================================================
// TARGET FLOOR
// =========================================================
reg [3:0] target_floor;


// =========================================================
// REQUEST PENDING FLAG
// =========================================================
//
// This flag prevents the same FIFO request from being
// read repeatedly while the elevator is idle.
//
// 0 = no request currently loaded
// 1 = a request is currently being processed
//
reg request_pending;


// =========================================================
// FIFO WRITE LOGIC
// =========================================================
//
// Whenever request_valid is 1 and FIFO is not full,
// store the requested floor in FIFO.
//
assign fifo_wr_en = request_valid && !fifo_full;


// =========================================================
// FIFO READ LOGIC
// =========================================================
//
// Read a new request when:
//
// 1. Elevator is IDLE
// 2. FIFO is NOT empty
// 3. No request is currently being processed.
always @(*) begin

    fifo_rd_en = 1'b0;

    if (elevator_idle &&!fifo_empty &&!request_pending)
    
    begin

        fifo_rd_en = 1'b1;

    end

end


// =========================================================
// REQUEST PENDING CONTROL
// =========================================================
//
// When FIFO read is requested, a request is being loaded.
//
// When elevator reaches the target floor and eventually
// returns to IDLE, clear the pending flag so the next
// FIFO request can be loaded.
//
// NOTE:
// fifo_data_valid occurs after the FIFO read.
//
always @(posedge clk or posedge rst) begin

    if (rst) 
    
    begin

        request_pending <= 1'b0;

    end

    else begin

        // A FIFO request has been successfully read
        if (fifo_data_valid) 
        
        begin

            request_pending <= 1'b1;

        end

        // Current request has been completed.
        // Elevator is idle and there is no new FIFO data
        // being loaded in this cycle.
        else if (elevator_idle && request_pending) 
        
        begin

            request_pending <= 1'b0;

        end

    end

end


// =========================================================
// TARGET FLOOR UPDATE
// =========================================================
//
// fifo_data_valid is a one-clock pulse generated by FIFO
// after a successful read.
//
// Therefore target_floor is updated only when valid data
// comes from FIFO.
//
always @(posedge clk or posedge rst) begin

    if (rst)

        target_floor <= 4'd0;

    else if ( current_floor==target_floor)

        target_floor <= fifo_data_out;

end


// =========================================================
// FIFO INSTANCE
// =========================================================
fifo_sync #(.fifo_depth(8),.data_width(4)) fifo_inst 

    (

    .clk(clk),
    .rst(rst),

    .cs(1'b1),

    // -------------------------
    // WRITE SIDE
    // -------------------------
    .w_enable(fifo_wr_en),
    .data_in(floor),

    // -------------------------
    // READ SIDE
    // -------------------------
    .r_enable(fifo_rd_en),
    .data_out(fifo_data_out),
    .data_valid(fifo_data_valid),

    // -------------------------
    // STATUS
    // -------------------------
    .full(fifo_full),
    .empty(fifo_empty)

);


// =========================================================
// ELEVATOR INSTANCE
// =========================================================
elevator elevator_inst 

(

    .clk(clk),
    .rst(rst),

    .electricity(electricity),
    .generator(generator),

    .up(up),
    .down(down),

    .e_stop(e_stop),
    .weight(weight),

    // Target floor comes from FIFO
    .floor(target_floor),

    .fan(fan),
    .light(light),

    // -------------------------
    // OUTPUTS
    // -------------------------
    .m_up(m_up),
    .m_down(m_down),

    .d_open(d_open),
    .d_close(d_close),

    .light_on(light_on),
    .fan_on(fan_on),
    .alarm_on(alarm_on),

    // -------------------------
    // STATUS
    // -------------------------
    .idle_check(elevator_idle),

    .current_floor(current_floor),
    .current_state(current_state)

);

endmodule